// This file is automatically generated by util_bio.pl
//   source: test_util_bio.bio
//   namespace: test_util_bio

#include "test_util_bio.bio.h"

int test_util_bio_Copy_fileHeader( test_util_bio_fileHeader_t* const dst, const test_util_bio_fileHeader_t* const src ) {
	size_t	len;

	dst->theFirst = src->theFirst;
	dst->theSecond = src->theSecond;
	dst->theThird = src->theThird;
	dst->theFourth = src->theFourth;
	len = dst->var_buf_777.len = src->var_buf_777.len;
	dst->var_buf_777.buf = malloc( len );
	if ( dst->var_buf_777.buf == NULL ) {
		return 0;	// ignoring this fatal error of malloc()
	}
	memcpy( dst->var_buf_777.buf, src->var_buf_777.buf, len );

	return 1;
}

int test_util_bio_IsEqual_fileHeader( const test_util_bio_fileHeader_t* const r1, const test_util_bio_fileHeader_t* const r2 ) {
	if ( r1->theFirst != r2->theFirst ) {
		return 0;
	}
	if ( r1->theSecond != r2->theSecond ) {
		return 0;
	}
	if ( r1->theThird != r2->theThird ) {
		return 0;
	}
	if ( r1->theFourth != r2->theFourth ) {
		return 0;
	}
	if ( !bbb_util_bio_IsEqual_varbuf( r1->var_buf_777, r2->var_buf_777 ) ) {
		return 0;
	}

	return 1;
}

size_t test_util_bio_GetSize_fileHeader( const test_util_bio_fileHeader_t* const r ) {
	return ( 0 + sizeof( uint8_t ) + sizeof( uint16_t ) + sizeof( uint32_t ) + sizeof( uint64_t ) + sizeof( r->var_buf_777.len ) + r->var_buf_777.len );
}

size_t test_util_bio_GetSizeArray_fileHeader( const test_util_bio_fileHeader_t* const a, size_t const n ) {
	size_t	i;
	size_t	sz = 0;

	for ( i = 0; i < n; i++ ) {
		sz += test_util_bio_GetSize_fileHeader( &( a[ i ] ) );
	}
	return sz;
}

size_t test_util_bio_ReadFromBuf_fileHeader( test_util_bio_fileHeader_t* const r, const bbb_byte_t* const buf, const size_t len ) {
	size_t	cur = 0;
	size_t	red;

	if ( cur >= len ) { return 0; }
	r->theFirst = *( buf + cur );
	cur++;
	red = bbb_util_bio_ReadFromBuf_uint16( &( r->theSecond ), buf + cur, len - cur );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromBuf_uint32( &( r->theThird ), buf + cur, len - cur );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromBuf_uint64( &( r->theFourth ), buf + cur, len - cur );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromBuf_varbuf( &( r->var_buf_777 ), buf + cur, len - cur );
	if ( red == 0 ) { return 0; }
	cur += red;
	return cur;
}

size_t test_util_bio_ReadFromBufArray_fileHeader( test_util_bio_fileHeader_t* const a, size_t const n, const bbb_byte_t* const buf, const size_t len ) {
	size_t	i;
	size_t	cur = 0;
	size_t	red;

	for ( i = 0; i < n; i++ ) {
		red = test_util_bio_ReadFromBuf_fileHeader( &( a[ i ] ), buf + cur, len - cur );
		if ( red == 0 ) { return 0; }
		cur += red;
	}
	return cur;
}

size_t test_util_bio_WriteToBuf_fileHeader( const test_util_bio_fileHeader_t* const r, bbb_byte_t* const buf, const size_t len ) {
	size_t	cur = 0;
	size_t	wtn;

	if ( cur >= len ) { return 0; }
	*( buf + cur ) = r->theFirst;
	cur++;
	wtn = bbb_util_bio_WriteToBuf_uint16( r->theSecond, buf + cur, len - cur );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToBuf_uint32( r->theThird, buf + cur, len - cur );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToBuf_uint64( r->theFourth, buf + cur, len - cur );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToBuf_varbuf( r->var_buf_777, buf + cur, len - cur );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	return cur;
}

size_t test_util_bio_WriteToBufArray_fileHeader( const test_util_bio_fileHeader_t* const a, size_t const n, bbb_byte_t* const buf, const size_t len ) {
	size_t	i;
	size_t	cur = 0;
	size_t	wtn;

	for ( i = 0; i < n; i++ ) {
		wtn = test_util_bio_WriteToBuf_fileHeader( &( a[ i ] ), buf + cur, len - cur );
		if ( wtn == 0 ) { return 0; }
		cur += wtn;
	}
	return cur;
}

size_t test_util_bio_ReadFromFile_fileHeader( test_util_bio_fileHeader_t* const r, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	cur = 0;
	size_t	red;

	if ( fread( &( r->theFirst ), 1, 1, f ) == 0 ) { return 0; }
	bbb_util_hash_UpdateChecksum( &( r->theFirst ), 1, chk );
	cur++;
	red = bbb_util_bio_ReadFromFile_uint16( &( r->theSecond ), f, chk );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromFile_uint32( &( r->theThird ), f, chk );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromFile_uint64( &( r->theFourth ), f, chk );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromFile_varbuf( &( r->var_buf_777 ), f, chk );
	if ( red == 0 ) { return 0; }
	cur += red;
	return cur;
}

size_t test_util_bio_ReadFromFileArray_fileHeader( test_util_bio_fileHeader_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	i;
	size_t	cur = 0;
	size_t	red;

	for ( i = 0; i < n; i++ ) {
		red = test_util_bio_ReadFromFile_fileHeader( &( a[ i ] ), f, chk );
		if ( red == 0 ) { return 0; }
		cur += red;
	}
	return cur;
}

size_t test_util_bio_WriteToFile_fileHeader( const test_util_bio_fileHeader_t* const r, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	cur = 0;
	size_t	wtn;

	bbb_util_hash_UpdateChecksum( &( r->theFirst ), 1, chk );
	if ( fwrite( &( r->theFirst ), 1, 1, f ) == 0 ) { return 0; }
	cur++;
	wtn = bbb_util_bio_WriteToFile_uint16( r->theSecond, f, chk );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToFile_uint32( r->theThird, f, chk );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToFile_uint64( r->theFourth, f, chk );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToFile_varbuf( r->var_buf_777, f, chk );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	return cur;
}

size_t test_util_bio_WriteToFileArray_fileHeader( const test_util_bio_fileHeader_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	i;
	size_t	cur = 0;
	size_t	wtn;

	for ( i = 0; i < n; i++ ) {
		wtn = test_util_bio_WriteToFile_fileHeader( &( a[ i ] ), f, chk );
		if ( wtn == 0 ) { return 0; }
		cur += wtn;
	}
	return cur;
}

void test_util_bio_Destroy_fileHeader( test_util_bio_fileHeader_t* const r ) {
	free( r->var_buf_777.buf );
	r->var_buf_777.buf = NULL;
	r->var_buf_777.len = 0;

	return;
}

void test_util_bio_DestroyEach_fileHeader( test_util_bio_fileHeader_t* const a, size_t const n ) {
	size_t	i;

	for ( i = 0; i < n; i++ ) {
		test_util_bio_Destroy_fileHeader( &( a[ i ] ) );
	}
}

int test_util_bio_Copy_ext333( test_util_bio_ext333_t* const dst, const test_util_bio_ext333_t* const src ) {
	size_t	len;

	len = dst->v1.len = src->v1.len;
	dst->v1.buf = malloc( len );
	if ( dst->v1.buf == NULL ) {
		return 0;	// ignoring this fatal error of malloc()
	}
	memcpy( dst->v1.buf, src->v1.buf, len );
	len = dst->v2.len = src->v2.len;
	dst->v2.buf = malloc( len );
	if ( dst->v2.buf == NULL ) {
		return 0;	// ignoring this fatal error of malloc()
	}
	memcpy( dst->v2.buf, src->v2.buf, len );

	return 1;
}

int test_util_bio_IsEqual_ext333( const test_util_bio_ext333_t* const r1, const test_util_bio_ext333_t* const r2 ) {
	if ( !bbb_util_bio_IsEqual_varbuf( r1->v1, r2->v1 ) ) {
		return 0;
	}
	if ( !bbb_util_bio_IsEqual_varbuf( r1->v2, r2->v2 ) ) {
		return 0;
	}

	return 1;
}

size_t test_util_bio_GetSize_ext333( const test_util_bio_ext333_t* const r ) {
	return ( 0 + sizeof( r->v1.len ) + r->v1.len + sizeof( r->v2.len ) + r->v2.len );
}

size_t test_util_bio_GetSizeArray_ext333( const test_util_bio_ext333_t* const a, size_t const n ) {
	size_t	i;
	size_t	sz = 0;

	for ( i = 0; i < n; i++ ) {
		sz += test_util_bio_GetSize_ext333( &( a[ i ] ) );
	}
	return sz;
}

size_t test_util_bio_ReadFromBuf_ext333( test_util_bio_ext333_t* const r, const bbb_byte_t* const buf, const size_t len ) {
	size_t	cur = 0;
	size_t	red;

	red = bbb_util_bio_ReadFromBuf_varbuf( &( r->v1 ), buf + cur, len - cur );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromBuf_varbuf( &( r->v2 ), buf + cur, len - cur );
	if ( red == 0 ) { return 0; }
	cur += red;
	return cur;
}

size_t test_util_bio_ReadFromBufArray_ext333( test_util_bio_ext333_t* const a, size_t const n, const bbb_byte_t* const buf, const size_t len ) {
	size_t	i;
	size_t	cur = 0;
	size_t	red;

	for ( i = 0; i < n; i++ ) {
		red = test_util_bio_ReadFromBuf_ext333( &( a[ i ] ), buf + cur, len - cur );
		if ( red == 0 ) { return 0; }
		cur += red;
	}
	return cur;
}

size_t test_util_bio_WriteToBuf_ext333( const test_util_bio_ext333_t* const r, bbb_byte_t* const buf, const size_t len ) {
	size_t	cur = 0;
	size_t	wtn;

	wtn = bbb_util_bio_WriteToBuf_varbuf( r->v1, buf + cur, len - cur );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToBuf_varbuf( r->v2, buf + cur, len - cur );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	return cur;
}

size_t test_util_bio_WriteToBufArray_ext333( const test_util_bio_ext333_t* const a, size_t const n, bbb_byte_t* const buf, const size_t len ) {
	size_t	i;
	size_t	cur = 0;
	size_t	wtn;

	for ( i = 0; i < n; i++ ) {
		wtn = test_util_bio_WriteToBuf_ext333( &( a[ i ] ), buf + cur, len - cur );
		if ( wtn == 0 ) { return 0; }
		cur += wtn;
	}
	return cur;
}

size_t test_util_bio_ReadFromFile_ext333( test_util_bio_ext333_t* const r, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	cur = 0;
	size_t	red;

	red = bbb_util_bio_ReadFromFile_varbuf( &( r->v1 ), f, chk );
	if ( red == 0 ) { return 0; }
	cur += red;
	red = bbb_util_bio_ReadFromFile_varbuf( &( r->v2 ), f, chk );
	if ( red == 0 ) { return 0; }
	cur += red;
	return cur;
}

size_t test_util_bio_ReadFromFileArray_ext333( test_util_bio_ext333_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	i;
	size_t	cur = 0;
	size_t	red;

	for ( i = 0; i < n; i++ ) {
		red = test_util_bio_ReadFromFile_ext333( &( a[ i ] ), f, chk );
		if ( red == 0 ) { return 0; }
		cur += red;
	}
	return cur;
}

size_t test_util_bio_WriteToFile_ext333( const test_util_bio_ext333_t* const r, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	cur = 0;
	size_t	wtn;

	wtn = bbb_util_bio_WriteToFile_varbuf( r->v1, f, chk );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	wtn = bbb_util_bio_WriteToFile_varbuf( r->v2, f, chk );
	if ( wtn == 0 ) { return 0; }
	cur += wtn;
	return cur;
}

size_t test_util_bio_WriteToFileArray_ext333( const test_util_bio_ext333_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	i;
	size_t	cur = 0;
	size_t	wtn;

	for ( i = 0; i < n; i++ ) {
		wtn = test_util_bio_WriteToFile_ext333( &( a[ i ] ), f, chk );
		if ( wtn == 0 ) { return 0; }
		cur += wtn;
	}
	return cur;
}

void test_util_bio_Destroy_ext333( test_util_bio_ext333_t* const r ) {
	free( r->v1.buf );
	r->v1.buf = NULL;
	r->v1.len = 0;

	free( r->v2.buf );
	r->v2.buf = NULL;
	r->v2.len = 0;

	return;
}

void test_util_bio_DestroyEach_ext333( test_util_bio_ext333_t* const a, size_t const n ) {
	size_t	i;

	for ( i = 0; i < n; i++ ) {
		test_util_bio_Destroy_ext333( &( a[ i ] ) );
	}
}
