// This file is automatically generated by util_bio.pl
//   source: test_util_bio.bio
//   namespace: test_util_bio

#ifndef _TEST_UTIL_BIO_BIO_H
#define _TEST_UTIL_BIO_BIO_H

#include "global.h"
#include "util_bio.h"

typedef struct {
	uint8_t			theFirst;
	uint16_t		theSecond;
	uint32_t		theThird;
	uint64_t		theFourth;
	bbb_varbuf_t	var_buf_777;
} test_util_bio_fileHeader_t;

int test_util_bio_Copy_fileHeader( test_util_bio_fileHeader_t* const dst, const test_util_bio_fileHeader_t* const src );
void test_util_bio_Destroy_fileHeader( test_util_bio_fileHeader_t* const r );
void test_util_bio_DestroyEach_fileHeader( test_util_bio_fileHeader_t* const a, size_t const n );
size_t test_util_bio_GetSize_fileHeader( const test_util_bio_fileHeader_t* const r );
int test_util_bio_IsEqual_fileHeader( const test_util_bio_fileHeader_t* const r1, const test_util_bio_fileHeader_t* const r2 );
int test_util_bio_Read_fileHeader( test_util_bio_fileHeader_t* const r, FILE* const f );
int test_util_bio_ReadArray_fileHeader( test_util_bio_fileHeader_t* const a, size_t const n, FILE* const f );
int test_util_bio_Write_fileHeader( const test_util_bio_fileHeader_t* const r, FILE* const f );
int test_util_bio_WriteArray_fileHeader( const test_util_bio_fileHeader_t* const a, size_t const n, FILE* const f );

typedef struct {
	bbb_varbuf_t	v1;
	bbb_varbuf_t	v2;
} test_util_bio_ext333_t;

int test_util_bio_Copy_ext333( test_util_bio_ext333_t* const dst, const test_util_bio_ext333_t* const src );
void test_util_bio_Destroy_ext333( test_util_bio_ext333_t* const r );
void test_util_bio_DestroyEach_ext333( test_util_bio_ext333_t* const a, size_t const n );
size_t test_util_bio_GetSize_ext333( const test_util_bio_ext333_t* const r );
int test_util_bio_IsEqual_ext333( const test_util_bio_ext333_t* const r1, const test_util_bio_ext333_t* const r2 );
int test_util_bio_Read_ext333( test_util_bio_ext333_t* const r, FILE* const f );
int test_util_bio_ReadArray_ext333( test_util_bio_ext333_t* const a, size_t const n, FILE* const f );
int test_util_bio_Write_ext333( const test_util_bio_ext333_t* const r, FILE* const f );
int test_util_bio_WriteArray_ext333( const test_util_bio_ext333_t* const a, size_t const n, FILE* const f );

#endif
