SRC = snapshot.c pack.c tools.c
CC_FLAGS = /nologo /D PLATFORM_WINDOWS #/D DEBUG
LK_FLAGS = /nologo
LIBS = -lssl

dripbix: dripbix.c $(SRC)
	cl $(CC_FLAGS) /c dripbix.c $(SRC)
	link $(LK_FLAGS) /out:dripbix.exe *.obj $(LIBS)

test: test.c minunit.h $(SRC)
	cl $(CC_FLAGS) test.c $(SRC) $(LIBS)

watcher: watcher.c
	cl watcher.c
