dripbix: dripbix.c \
	snapshot.c snapshot.h \
	pack.c pack.h \
	morph.c morph.h \
	tools.c tools.h
	cl /nologo /c dripbix.c snapshot.c pack.c morph.c tools.c /D PLATFORM_WINDOWS
	link /nologo /out:dripbix.exe *.obj ws2_32.lib

test: test.c minunit.h \
	tools.c tools.h
	cl test.c tools.c

watcher: watcher.c
	cl watcher.c
