SRC = snapshot.c pack.c tools.c
CC_FLAGS = /nologo /D PLATFORM_WINDOWS /I OpenSSL-Win32\include #/D DEBUG
LK_FLAGS = /nologo
LIBS = ws2_32.lib OpenSSL-Win32\lib\libeay32.lib

dripbix: dripbix.c $(SRC)
	cl $(CC_FLAGS) /c dripbix.c $(SRC)
	link $(LK_FLAGS) /out:dripbix.exe *.obj $(LIBS)
	copy /Y dripbix.exe bin\windows

test: test.c minunit.h $(SRC)
	cl $(CC_FLAGS) test.c $(SRC) $(LIBS)
	copy /Y test.exe bin\windows

watcher: watcher.c
	cl watcher.c
