SRC = snapshot.c pack.c tools.c
CC_FLAGS = -DPLATFORM_LINUX #-DDEBUG

dripbix: dripbix.c $(SRC)
	gcc $(CC_FLAGS) -o dripbix dripbix.c $(SRC)

test: test.c minunit.h $(SRC)
	gcc $(CC_FLAGS) -o test test.c $(SRC)

watcher: watcher.c
	gcc watcher.c -o watcher
