#
# PerlPP (PPP): Perl preprocessor
#
# http://darkness.codefu.org/wordpress/2003/03/perl-scoping/

package PerlPP;

use strict;
use warnings;
#use Data::Dumper;

my $TAG_OPEN = "<[?]";
my $TAG_CLOSE = "[?]>";

my $filename = "";
my $outFilename = "";
my $package = "";
my $srcType = "";
my $code = "";
my $plain = "";
my $f;
my $PerlPP_out;

sub OutputPlain {
	$code .= "print \$PerlPP_out '" . $plain =~ s/'/\\'/gr . "';";
	$plain = "";
}

( $filename = shift ) and ( $outFilename = shift ) or die "Usage: perl perlpp.pl <inFilename> <outFilename>\n";
$package = ( $filename =~ s/^([a-zA-Z_][a-zA-Z_0-9.]*).p$/$1/r );
$package =~ s/\./_/g;
$srcType = ( shift ) || "c";

open $f, $filename or die $!;

OPENING:
while ( <$f> ) {
	if ( /^(.*?)$TAG_OPEN(.*)$/ ) {
		$plain .= $1;
		&OutputPlain;

		$_ = $2 . "\n";
		
		CLOSING:
		if ( /^(.*?)$TAG_CLOSE(.*)$/ ) {
			$code .= $1;
			$_ = $2 . "\n";
			redo OPENING;
		} else {
			$code .= $_ . "\n";
			$_ = <$f>;
			goto CLOSING;
		};
	} else {
		$plain .= $_;
	}
}
&OutputPlain;

close $f or die $!;

open $PerlPP_out, ">", "${outFilename}" or die $!;
if ( $srcType =~ /^[ch]$/ ) {
	print $PerlPP_out "// This file is automatically generated by perlpp.pl\n";
	print $PerlPP_out "//   source: $filename\n";
	print $PerlPP_out "//   package: $package\n\n";
} else {
	print "Unknown type of a source code. Comments were not added.\n";
}
eval( "package PPP_${package}; use strict; use warnings; sub echo { print \$PerlPP_out shift; }\n" . $code );
warn $@ if $@;
close $PerlPP_out or die $!;
