// This file is automatically generated by bio.pl
//   source: sshot_file.bio
//   namespace: bbb_sshot_file

#ifndef _BBB_SSHOT_FILE_BIO_H
#define _BBB_SSHOT_FILE_BIO_H

#include "global.h"
#include "bio.h"

typedef struct {
	uint8_t			magic;
	uint8_t			runtime;
	uint8_t			platform;
	uint8_t			format;
} bbb_sshot_file_hdr_t;

int		bbb_sshot_file_Copy_hdr( bbb_sshot_file_hdr_t* const dst, const bbb_sshot_file_hdr_t* const src );
void	bbb_sshot_file_Destroy_hdr( bbb_sshot_file_hdr_t* const r );
void	bbb_sshot_file_DestroyEach_hdr( bbb_sshot_file_hdr_t* const a, size_t const n );
size_t	bbb_sshot_file_GetSize_hdr( const bbb_sshot_file_hdr_t* const r );
size_t	bbb_sshot_file_GetSizeArray_hdr( const bbb_sshot_file_hdr_t* const a, size_t const n );
int		bbb_sshot_file_IsEqual_hdr( const bbb_sshot_file_hdr_t* const r1, const bbb_sshot_file_hdr_t* const r2 );
size_t	bbb_sshot_file_ReadFromBuf_hdr( bbb_sshot_file_hdr_t* const r, const bbb_byte_t* const buf, const size_t len );
size_t	bbb_sshot_file_ReadFromBufArray_hdr( bbb_sshot_file_hdr_t* const a, size_t const n, const bbb_byte_t* const buf, const size_t len );
size_t	bbb_sshot_file_ReadFromFile_hdr( bbb_sshot_file_hdr_t* const r, FILE* const f, bbb_checksum_t* const chk );
size_t	bbb_sshot_file_ReadFromFileArray_hdr( bbb_sshot_file_hdr_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk );
size_t	bbb_sshot_file_WriteToBuf_hdr( const bbb_sshot_file_hdr_t* const r, bbb_byte_t* const buf, const size_t len );
size_t	bbb_sshot_file_WriteToBufArray_hdr( const bbb_sshot_file_hdr_t* const a, size_t const n, bbb_byte_t* const buf, const size_t len );
size_t	bbb_sshot_file_WriteToFile_hdr( const bbb_sshot_file_hdr_t* const r, FILE* const f, bbb_checksum_t* const chk );
size_t	bbb_sshot_file_WriteToFileArray_hdr( const bbb_sshot_file_hdr_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk );

#endif
