// This file is automatically generated by util_bio.pl
//   source: sshot_file.bio
//   namespace: sshot_file

#include "sshot_file.bio.h"
size_t sshot_file_Read_hdr( sshot_file_hdr_t* const r, FILE* const f ) {
	if ( fread( &( r->magic ), 1, 1, f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Read_uint16( &( r->runtime ), f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Read_uint32( &( r->platform ), f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Read_uint64( &( r->ssFileVersion ), f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Read_varbuf( &( r->vb ), f ) == 0 ) {
		return 0;
	}

	return 1;
}

size_t sshot_file_ReadArray_hdr( sshot_file_hdr_t* const a, size_t const n, FILE* const f ) {
	size_t i;

	for ( i = 0; i < n; i++ ) {
		if ( sshot_file_Read_hdr( &( a[ i ] ), f ) == 0 ) {
			return 0;
		}
	}
	return 1;
}

size_t sshot_file_Write_hdr( const sshot_file_hdr_t* const r, FILE* const f ) {
	if ( fwrite( &( r->magic ), 1, 1, f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Write_uint16( r->runtime, f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Write_uint32( r->platform, f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Write_uint64( r->ssFileVersion, f ) == 0 ) {
		return 0;
	}

	if ( bbb_util_bio_Write_varbuf( r->vb, f ) == 0 ) {
		return 0;
	}

	return 1;
}

size_t sshot_file_WriteArray_hdr( const sshot_file_hdr_t* const a, size_t const n, FILE* const f ) {
	size_t i;

	for ( i = 0; i < n; i++ ) {
		if ( sshot_file_Write_hdr( &( a[ i ] ), f ) == 0 ) {
			return 0;
		}
	}
	return 1;
}

void sshot_file_Destroy_hdr( sshot_file_hdr_t* const r ) {
	free( r->vb.buf );
	r->vb.buf = NULL;
	r->vb.len = 0;

	return;
}

void sshot_file_DestroyEach_hdr( sshot_file_hdr_t* const a, size_t const n ) {
	size_t i;

	for ( i = 0; i < n; i++ ) {
		sshot_file_Destroy_hdr( &( a[ i ] ) );
	}
}

