// This file is automatically generated by util_bio.pl
//   source: sshot_file.bio
//   namespace: sshot_file

#ifndef _SSHOT_FILE_BIO_H
#define _SSHOT_FILE_BIO_H

#include "global.h"
#include "util_bio.h"

typedef struct {
	uint8_t			magic;
	uint16_t		runtime;
	uint32_t		platform;
	uint64_t		ssFileVersion;
	bbb_varbuf_t	vb;
} sshot_file_hdr_t;

void sshot_file_Destroy_hdr( sshot_file_hdr_t* const r );
void sshot_file_DestroyEach_hdr( sshot_file_hdr_t* const a, size_t const n );
size_t sshot_file_Read_hdr( sshot_file_hdr_t* const r, FILE* const f );
size_t sshot_file_ReadArray_hdr( sshot_file_hdr_t* const a, size_t const n, FILE* const f );
size_t sshot_file_Write_hdr( const sshot_file_hdr_t* const r, FILE* const f );
size_t sshot_file_WriteArray_hdr( const sshot_file_hdr_t* const a, size_t const n, FILE* const f );

#endif
