// This file is automatically generated by bio.pl
//   source: sshot_file.bio
//   namespace: bbb_sshot_file

#include "sshot_file.bio.h"

int bbb_sshot_file_Copy_hdr( bbb_sshot_file_hdr_t* const dst, const bbb_sshot_file_hdr_t* const src ) {
	dst->magic = src->magic;
	dst->runtime = src->runtime;
	dst->platform = src->platform;
	dst->format = src->format;

	return 1;
}

int bbb_sshot_file_IsEqual_hdr( const bbb_sshot_file_hdr_t* const r1, const bbb_sshot_file_hdr_t* const r2 ) {
	if ( r1->magic != r2->magic ) {
		return 0;
	}
	if ( r1->runtime != r2->runtime ) {
		return 0;
	}
	if ( r1->platform != r2->platform ) {
		return 0;
	}
	if ( r1->format != r2->format ) {
		return 0;
	}

	return 1;
}

size_t bbb_sshot_file_GetSize_hdr( const bbb_sshot_file_hdr_t* const r ) {
	return ( 0 + sizeof( r->magic ) + sizeof( r->runtime ) + sizeof( r->platform ) + sizeof( r->format ) );
}

size_t bbb_sshot_file_GetSizeArray_hdr( const bbb_sshot_file_hdr_t* const a, size_t const n ) {
	size_t	i;
	size_t	sz = 0;

	for ( i = 0; i < n; i++ ) {
		sz += bbb_sshot_file_GetSize_hdr( &( a[ i ] ) );
	}
	return sz;
}

size_t bbb_sshot_file_ReadFromBuf_hdr( bbb_sshot_file_hdr_t* const r, const bbb_byte_t* const buf, const size_t len ) {
	size_t	cur = 0;
	if ( cur >= len ) {
		return 0;
	}
	r->magic = *( buf + cur );
	cur++;
	if ( cur >= len ) {
		return 0;
	}
	r->runtime = *( buf + cur );
	cur++;
	if ( cur >= len ) {
		return 0;
	}
	r->platform = *( buf + cur );
	cur++;
	if ( cur >= len ) {
		return 0;
	}
	r->format = *( buf + cur );
	cur++;
	return cur;
}

size_t bbb_sshot_file_ReadFromBufArray_hdr( bbb_sshot_file_hdr_t* const a, size_t const n, const bbb_byte_t* const buf, const size_t len ) {
	size_t	i;
	size_t	cur = 0;
	size_t	red;

	for ( i = 0; i < n; i++ ) {
		red = bbb_sshot_file_ReadFromBuf_hdr( &( a[ i ] ), buf + cur, len - cur );
		if ( red == 0 ) {
			return 0;
		}
		cur += red;
	}
	return cur;
}

size_t bbb_sshot_file_WriteToBuf_hdr( const bbb_sshot_file_hdr_t* const r, bbb_byte_t* const buf, const size_t len ) {
	size_t	cur = 0;
	if ( cur >= len ) { return 0; }
	*( buf + cur ) = r->magic;
	cur++;
	if ( cur >= len ) { return 0; }
	*( buf + cur ) = r->runtime;
	cur++;
	if ( cur >= len ) { return 0; }
	*( buf + cur ) = r->platform;
	cur++;
	if ( cur >= len ) { return 0; }
	*( buf + cur ) = r->format;
	cur++;
	return cur;
}

size_t bbb_sshot_file_WriteToBufArray_hdr( const bbb_sshot_file_hdr_t* const a, size_t const n, bbb_byte_t* const buf, const size_t len ) {
	size_t	i;
	size_t	cur = 0;
	size_t	wtn;

	for ( i = 0; i < n; i++ ) {
		wtn = bbb_sshot_file_WriteToBuf_hdr( &( a[ i ] ), buf + cur, len - cur );
		if ( wtn == 0 ) { return 0; }
		cur += wtn;
	}
	return cur;
}

size_t bbb_sshot_file_ReadFromFile_hdr( bbb_sshot_file_hdr_t* const r, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	cur = 0;
	if ( fread( &( r->magic ), 1, 1, f ) == 0 ) {
		return 0;
	}
	bbb_util_hash_UpdateChecksum( &( r->magic ), 1, chk );
	cur++;
	if ( fread( &( r->runtime ), 1, 1, f ) == 0 ) {
		return 0;
	}
	bbb_util_hash_UpdateChecksum( &( r->runtime ), 1, chk );
	cur++;
	if ( fread( &( r->platform ), 1, 1, f ) == 0 ) {
		return 0;
	}
	bbb_util_hash_UpdateChecksum( &( r->platform ), 1, chk );
	cur++;
	if ( fread( &( r->format ), 1, 1, f ) == 0 ) {
		return 0;
	}
	bbb_util_hash_UpdateChecksum( &( r->format ), 1, chk );
	cur++;
	return cur;
}

size_t bbb_sshot_file_ReadFromFileArray_hdr( bbb_sshot_file_hdr_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	i;
	size_t	cur = 0;
	size_t	red;

	for ( i = 0; i < n; i++ ) {
		red = bbb_sshot_file_ReadFromFile_hdr( &( a[ i ] ), f, chk );
		if ( red == 0 ) {
			return 0;
		}
		cur += red;
	}
	return cur;
}

size_t bbb_sshot_file_WriteToFile_hdr( const bbb_sshot_file_hdr_t* const r, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	cur = 0;
	bbb_util_hash_UpdateChecksum( &( r->magic ), 1, chk );
	if ( fwrite( &( r->magic ), 1, 1, f ) == 0 ) { return 0; }
	cur++;
	bbb_util_hash_UpdateChecksum( &( r->runtime ), 1, chk );
	if ( fwrite( &( r->runtime ), 1, 1, f ) == 0 ) { return 0; }
	cur++;
	bbb_util_hash_UpdateChecksum( &( r->platform ), 1, chk );
	if ( fwrite( &( r->platform ), 1, 1, f ) == 0 ) { return 0; }
	cur++;
	bbb_util_hash_UpdateChecksum( &( r->format ), 1, chk );
	if ( fwrite( &( r->format ), 1, 1, f ) == 0 ) { return 0; }
	cur++;
	return cur;
}

size_t bbb_sshot_file_WriteToFileArray_hdr( const bbb_sshot_file_hdr_t* const a, size_t const n, FILE* const f, bbb_checksum_t* const chk ) {
	size_t	i;
	size_t	cur = 0;
	size_t	wtn;

	for ( i = 0; i < n; i++ ) {
		wtn = bbb_sshot_file_WriteToFile_hdr( &( a[ i ] ), f, chk );
		if ( wtn == 0 ) { return 0; }
		cur += wtn;
	}
	return cur;
}

void bbb_sshot_file_Destroy_hdr( bbb_sshot_file_hdr_t* const r ) {
	( void ) r;
}

void bbb_sshot_file_DestroyEach_hdr( bbb_sshot_file_hdr_t* const a, size_t const n ) {
	( void ) a;
	( void ) n;
}
