#
# PerlPP (PPP): Perl preprocessor
#
# Usage: perl perlpp.pl [options] <inFilename> <outFilename>
#
# Some info about scoping in Perl:
# http://darkness.codefu.org/wordpress/2003/03/perl-scoping/
#

package PerlPP;

use strict;
use warnings;

my $TAG_OPEN = "<?";
my $TAG_CLOSE = "?>";

my $argCommentsType = "";
my $argEval = "";
my $argDebug = 0;

my $filename = "";
my $outFilename = "";
my $package = "";
my $echoMode = 0;
my $commandMode = 0;
my $catching = 0;
my $wasCatched = 0;
my $code = "";
my $plain = "";
my $f;
my $PerlPP_out;
my $PerlPP_cGuard = "";
my %PerlPP_prefixes = ();

sub OutputPlain {
	my $_;

	foreach ( keys %PerlPP_prefixes ) {
		$plain =~ s/(^|\W)\Q$_\E/$1$PerlPP_prefixes{ $_ }/g;
	}
	$plain =~ s/\\/\\\\/g;
	$plain =~ s/'/\\'/g;

	if ( $catching ) {
		$code .= "'${plain}'";
	} else {
		$code .= "print \$PerlPP_out '${plain}';\n";
	}
	$plain = "";
}

sub OutputComments {
	my $prefix = "";

	if ( $argCommentsType eq "doubleslash" ) {
		$prefix = "//";
	} elsif ( $argCommentsType eq "hash" ) {
		$prefix = "#";
	} else {
		print "Unknown type of comments style.\n";
		return;
	}

	print $PerlPP_out "${prefix} This file is automatically generated by perlpp.pl\n";
	print $PerlPP_out "${prefix}   source: $filename\n";
	print $PerlPP_out "${prefix}   package: $package\n\n";
}

sub ProcessCommand {
	my $cmd = shift;

	if ( $cmd =~ /^prefix\s+(\S+)\s+(\S+)\s*$/ ) {
		$PerlPP_prefixes{ $1 } = $2;
	} elsif ( $cmd =~ /^c:guard\s*$/ ) {
		$PerlPP_cGuard = "_PPP_CGUARD_" . uc( $package );
		$plain .= "#ifndef ${PerlPP_cGuard}\n#define ${PerlPP_cGuard}\n"
	} else {
		die "Unknown command: ${cmd}";
	}
}

while ( my $a = shift ) {
	if ( $a eq "--eval" ) {
		$argEval .= ( shift ) || "";
	} elsif ( $a eq "--debug" ) {
		$argDebug = 1;
	} elsif ( $a eq "--comments" ) {
		$argCommentsType = ( shift ) || "";
	} else {
		$filename = $a;
		( $outFilename = shift ) or die "Usage: perl perlpp.pl [options] <inFilename> <outFilename>\n";
	}
}

$package = $filename;
$package =~ s/^([a-zA-Z_][a-zA-Z_0-9.]*).p$/$1/;
$package =~ s/[.\/\\]/_/g;
$code = "package PPP_${package}; use strict; use warnings;\n";
$code .= "sub echo { print \$PerlPP_out shift; }\n";
$code .= "${argEval}\n";

open $f, "<", $filename or die $!;

OPENING:
while ( <$f> ) {
	if ( /^(.*?)\Q$TAG_OPEN\E(.*)$/ ) {
		my $after = $2;
		my $inside = "";

		$plain .= $1;
		&OutputPlain;

		$wasCatched = 0;
		if ( $catching ) {
			if ( $after =~ /^"/ ) {
				$catching = 0;
				$wasCatched = 1;
				$_ = substr( $after, 1 ) . "\n";
			} else {
				die "Unfinished catching.";
			}
		} else {
			if ( $after =~ /^=/ ) {
				$echoMode = 1;
				$_ = substr( $after, 1 ) . "\n";
			} elsif ( $after =~ /^:/ ) {
				$commandMode = 1;
				$_ = substr( $after, 1 ) . "\n";
			} elsif ( $after =~ /^"/ ) {
				die "Unexpected end of catching, it was not started.";
			} else {
				$_ = $after . "\n";
			}
		}

		CLOSING:
		if ( /^(.*?)\Q$TAG_CLOSE\E(.*)$/ ) {
			$inside .= $1;
			$_ = $2 . "\n";
			if ( $inside =~ /"$/ ) {
				$catching = 1;
				$inside = substr( $inside, 0, -1 );
				if ( $echoMode ) {
					if ( $wasCatched ) {
						$code .= $inside;							# middle part of print() statement
					} else {
						$code .= "print \$PerlPP_out ( ${inside}";	# the start of print() statement
					}
					# echoMode is transparent for catching
				} elsif ( $commandMode ) {
					die "Catching inside a command mode is not allowed.";
				} else {
					$code .= $inside;
				}
			} else {
				if ( $echoMode ) {
					if ( $wasCatched ) {
						$code .= " );\n";							# the end of print() statement
					} else {
						$code .= "print \$PerlPP_out ( ${inside} );\n";
					}
					$echoMode = 0;
				} elsif ( $commandMode ) {
					ProcessCommand( $inside );
					$commandMode = 0;
				} else {
					$code .= $inside;
				}
			}
			redo OPENING;
		} else {
			$inside .= $_;
			$_ = <$f>;
			goto CLOSING;
		};
	} else {
		$plain .= $_;
	}
}

if ( $catching ) {
	die "Unfinished catching.";
}
if ( $PerlPP_cGuard ) {
	$plain .= "\n#endif		// ${PerlPP_cGuard}\n";
}
&OutputPlain;

close $f or die $!;

if ( $argDebug ) {
	print( $code );
} else {
	open $PerlPP_out, ">", "${outFilename}.tmp" or die $!;
	&OutputComments;
	eval( $code );
	warn $@ if $@;
	close $PerlPP_out or die $!;
    rename "${outFilename}.tmp", $outFilename;
}
